################################
# Outputs for Jenkins Master
################################
output "jenkins_master_public_ip" {
  description = "Public IP of Jenkins Master"
  value       = aws_instance.jenkins_master.public_ip
}

output "jenkins_master_private_ip" {
  description = "Private IP of Jenkins Master"
  value       = aws_instance.jenkins_master.private_ip
}


################################
# Outputs for Jenkins Agent
################################
output "jenkins_agent_public_ip" {
  description = "Public IP of Jenkins Agent"
  value       = aws_instance.jenkins_agent.public_ip
}

output "jenkins_agent_private_ip" {
  description = "Private IP of Jenkins Agent"
  value       = aws_instance.jenkins_agent.private_ip
}

################################
# SSH Key Location (generated by Terraform)
################################
output "jenkins_master_private_key_path" {
  description = "Path to private SSH key used for master-agent connection"
  value       = local_sensitive_file.private_key.filename
  sensitive   = true
}